[pytest]
testpaths = tests
base_url = https://www.saucedemo.com
addopts = -v --alluredir=allure-results
markers =
    login: pruebas de autenticacion
    carrito: pruebas del carrito de compras
    ordenamiento: pruebas de ordenamiento de productos
    checkout: pruebas del flujo de compra
    logout: pruebas de cierre de sesion
